"""models avatar

Revision ID: f3a7d5bfddc5
Revises: d9b3b1d43e1a
Create Date: 2026-05-04 18:17:19.509059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3a7d5bfddc5'
down_revision: Union[str, Sequence[str], None] = 'd9b3b1d43e1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('avatar', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('authors', 'avatar')
    # ### end Alembic commands ###
